Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-09, with the labels that each got.

#299 feat(npg): [CHK-1840] add update auth status npg request body choose
  api-spec/transactions-api.yaml
Labels: size/small, minor, chart-minor

#300 feat(npg): CHK-1833 add npg confirm payment in auth handler
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
Labels: size/small, minor, chart-minor

#302 fix(helm-configuration): increase initialDelaySeconds for DEV env
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#304 fix(configuration): CHK-1688 modified jwt validity
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/utils/JwtTokenUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#303 [CHK-1850] feat(update-auth-request): handle NPG notify request
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Labels: size/small, minor, chart-minor

#306 fix: api client base path
  src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
Labels: size/small, patch, chart-patch

#307 feat(CR pipeline) CHK-1882 integration test CR pipeline
  .devops/code-review-pipelines.yml
Labels: size/small, minor, chart-minor

#308 fix(CR pipeline): fixed path collection tests into ecommerce local
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release

#310 Fix NPG logic for handle orderId
  api-spec/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
Labels: size/small

#309 fix(deploy): fix NPG url for DEV and UAT envs
  .env.example
  README.md
  api-spec/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#323 feat(get-transaction): handling for view v2 (#7)
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/AddUserReceiptData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Labels: minor, chart-minor

#325 Chk 1921 authorization update handler (#3)
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/AddUserReceiptData.java
  src/main/java/it/pagopa/transactions/commands/data/ClosureSendData.java
  src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureErrorProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureSendProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/RefundRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureErrorProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureSendProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/RefundRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/RefundRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Labels: minor, chart-minor

#324 Chk 1921 v2 request authorization handler (#2)
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/data/AddUserReceiptData.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/data/ClosureSendData.java
  src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureErrorProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureSendProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/RefundRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureErrorProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureSendProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/RefundRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/RefundRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/java/it/pagopa/transactions/utils/TransactionsUtilsTest.java
Labels: minor, chart-minor

#312 [CHK-1910] Use npg gateway constant
  api-spec/transactions-api.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
Labels: size/small, patch, chart-patch
