Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-07, with the labels that each got.

#263 [CHK-1671] add application properties to enable light allccp check
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/resources/application-tests.properties
Labels: size/small

#266 fix(close payment branch): restore main branch for close payment openapi
  pom.xml
Labels: size/small

#267 [CHK-1692] fix(activation): propagate verification due date
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Labels: size/small

#268 [CHK-1693] update transaction status constant
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Labels: size/small

#269 Chk 1694 fix deploy pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#270 feat(CD): deploy on PR merge
  .devops/deploy-pipelines.yml
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  README.md
Labels: skip-release

#271 fix(deploy-pipeline): prod manual approval depends on green api tests
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#272 fix(dedploy-pipeline): api test UAT green
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#273 fix(deploy-pipeline): UAT green api test condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#274 fix(deploy-pipeline): UAT api test condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#276 fix: pr number extraction
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#277 feat(paymentMethodDescription) saved paymentMethodDescription into authorizationRequestEvent
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
Labels: size/small, minor, chart-minor

#278 fix(email validation): make email validation case insensitive
  api-spec/transactions-api.yaml
  pom.xml
  src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
Labels: size/small, patch, chart-patch

#279 [CHK-1718] update card logo refs
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#265 [CHK-1565] feat(tracing): implement tracing context propagation for expiration
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/java/it/pagopa/transactions/configurations/OpenTelemetryConfiguration.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
Labels: size/small, patch, chart-patch

#283 [CHK-1565] feat(tracing): add queue tracing to `TransactionRequestUserReceiptHandler`
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
Labels: size/small, patch, chart-patch

#285 feat(monitoring): trace Nodo fault code into custom open telemetry span
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/java/it/pagopa/transactions/utils/OpenTelemetryUtilsTest.java
Labels: size/small, minor, chart-minor

#282 [CHK-1565] feat(tracing): add queue tracing to `TransactionUserCancelHandler`
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
Labels: size/small, patch, chart-patch

#281 [CHK-1565] feat(tracing): add queue client with tracing to `TransactionSendClosureHandler`
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Labels: size/small, patch, chart-patch
