Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-10, with the labels that each got.

#331 fix(circuit-breaker): circuit breaker config
  src/main/resources/application.yml
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
Labels: size/small, patch, chart-patch

#311 CHK-1905 : feat(jwt): added claim ORDER_ID into jwt
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/utils/JwtTokenUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
Labels: size/large, minor, chart-minor

#335 CHK 1951: feat post transaction v2
  api-spec/v1/transactions-api.yaml
  api-spec/v2/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
  src/main/java/it/pagopa/transactions/commands/data/NewTransactionRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/JwtTokenUtils.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
  src/test/java/it/pagopa/transactions/utils/TransactionsUtilsTest.java
Labels: size/large, minor, chart-minor

#341 fix(env): modified WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX for helm dev
  helm/values-dev.yaml
Labels: size/small, patch, chart-patch

#342 feat(nodo): CHK-1929 add env for clientid used for closepayment
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/resources/application.properties
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#336 CHK-1973: feat(PATCH): added rrn into PATH npg details
  api-spec/v1/transactions-api.yaml
Labels: size/small, minor, chart-minor

#338 Chk 1919 npg notify logo
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/BrandLogoConfig.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/java/it/pagopa/transactions/utils/LogoMappingUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/configurations/BrandLogoConfigTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor

#343 fix(npg): return order id into auth requested response
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, patch, chart-patch

#345 fix(dev-conf): add nexi and amex for NPG psp key check
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#344 feat(CR pipeline): api tests NPG/PGS
  .devops/code-review-pipelines.yml
Labels: size/small, chart-patch, ignore-for-release

#346 feat(deploy pipeline): CHK-1999 e2e tests
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#347 feat(deploy pipeline): CHK-1870 api tests for NPG
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#348 feat: [CHK-2004] - save session id returned in NPG confirm payment
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
Labels: size/small, minor, chart-minor

#351 fix: use transaction service status enumeration
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
Labels: size/small, patch, chart-patch
