Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-08, with the labels that each got.

#286 fix(circuit-breaker): remove misconfigured circuit breaker
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
Labels: size/small, patch, chart-patch

#287 fix(monitoring): add tracing for nodo ok activation operations
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Labels: size/small, patch, chart-patch

#284 [CHK-1565] feat(tracing): make traced `QueueAsyncClient` the default
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
Labels: size/small, patch, chart-patch

#289 fix(monitoring): add transaction info into MDC
  src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
  src/main/java/it/pagopa/transactions/mdcutilities/MDCContextLifter.java
  src/main/java/it/pagopa/transactions/mdcutilities/MDCFilter.java
  src/main/java/it/pagopa/transactions/mdcutilities/TransactionTracingUtils.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#288 feat(closepayment): CHK-1769 base64 transactionId as rrn for xpay
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Labels: size/small, minor, chart-minor

#292 fix: enable OpenTelemetry log sending
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#291 feat(npg): [CHK-1782] update commons library
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#294 fix(helm-values): fixed integer parameters as string
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#293 [CHK-1829] feat(auth-request): add auth request details for NPG authorization
  api-spec/transactions-api.yaml
Labels: size/small, minor, chart-minor

#298 [CHK-1787] feat(commons): update commons version
  pom.xml
  src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
  src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
Labels: size/small, patch, chart-patch

#296 feat(npg-integration): [CHK-1832] handle psp api keys for each payment method
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#297 feat(npg): CHK 1831 retrieve bin from payment method service
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/services/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
  src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Labels: size/small, minor, chart-minor
