Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-12, with the labels that each got.

#374 feat: disable sendPaymentResult for expired transactions
  helm/values-prod.yaml
Labels: size/small, minor, chart-minor

#376 fix: [CHK-2221] - close payment additional info timestamp operation
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandlerTest.java
Labels: size/small, patch, chart-patch

#369 CHK-2188 feat: auth request with wallet
  .env.example
  README.md
  api-spec/v1/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/PagopaEcommerceTransactionsApplication.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/client/WalletClient.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/NpgSessionUrlConfig.java
  src/main/java/it/pagopa/transactions/configurations/RedisConfig.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/main/java/it/pagopa/transactions/repositories/TransactionCacheInfo.java
  src/main/java/it/pagopa/transactions/repositories/TransactionTemplateWrapper.java
  src/main/java/it/pagopa/transactions/repositories/WalletPaymentInfo.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/PaymentSessionData.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/client/WalletClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/configurations/WebClientsConfigTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/resources/application-tests.properties
Labels: size/large, minor, chart-minor

#380 CHK-2249 fix: authorization url for wallet payment
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, minor, chart-minor

#381 fix: outcome and cancel path for wallet payment flow
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
Labels: size/small, skip-release

#378 [CHK-2230] feat(jwt token utils): use commons jwt token utils
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/configurations/SecretsConfigurations.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/JWTTokenGenerationException.java
  src/main/java/it/pagopa/transactions/utils/JwtTokenUtils.java
  src/main/java/it/pagopa/transactions/utils/LogoMappingUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/NpgNotificationUrlMatcher.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor

#384 Chk 2263 minpods deploy
  helm/values-prod.yaml
Labels: size/small, minor, chart-minor

#386 Restore update strategy for prod
  helm/values-prod.yaml
Labels: size/small, skip-release, ignore-for-release
