Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2023-11, with the labels that each got.

#352 feat(ff): CHK-2091 add feature flag to enable sendpaymentresult for expired transactions
  .env.example
  .env.intellij.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#353 chore(configuration): add unicredit psp configuration
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#330 feat: disable log apm send
  helm/values-prod.yaml
Labels: size/small

#354 feat: CHK-2091 delete ff sendPamentResult for V2
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
Labels: size/small, patch, chart-patch

#360 feat(npg): [CHK-2114] commons npg api key parsing logic
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfig.java
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigBuilder.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigTest.java
Labels: size/small, minor, chart-minor

#361 feat: update psp for npg
  helm/values-dev.yaml
Labels: size/small, minor, chart-minor

#366 fix: add nodo close payment response outcome logging
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
Labels: size/small, patch, chart-patch

#358 feat(availability): CHK-2075 add antiPodAffinity for prod
  helm/values-prod.yaml
Labels: size/small, minor, chart-minor

#367 fix(logging): fix wrong transaction status log
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
Labels: size/small, patch, chart-patch

#364 fix: [CHK-2120] - parameterize close payment path
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch
