Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-02, with the labels that each got.

#413 feat: add update transaction status tracing for redirect transactions
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: minor, chart-minor

#416 feat: NPG error code mapping
  api-spec/v1/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Labels: size/small, minor, chart-minor

#412 feat(redirect outcome): add patch handling for REDIRECT payment flow
  api-spec/v1/transactions-api.yaml
  src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusDataTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: size/large, minor, chart-minor

#403 [CHK-2368] feat(redirect): add `touchpoint` parameter to Redirect url retrieval PSP API
  api-spec/client/openapi/redirect/redirect-api.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#419 feat: add CR api tests for redirect payment flow
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release

#387 [CHK-2259] fixed: logo configuration with new CDN reference
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, minor, chart-minor

#421 [CHK-2334] fix(deps): mark `netty-resolver-dns-native-macos` dependency for test only as it causes memleak in prod
  pom.xml
Labels: size/small, patch, chart-patch

#426 fix(cache-invalidation): invalidate cache after auth request
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#428 Chk-2465: restrict refund in closure handler
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
Labels: size/small, patch, chart-patch

#429 chore(conf): discriminate queues and node close payment for blue instance
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#423 [CHK 2443] used correlation saved into activated event into NPG call
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, minor, chart-minor

#420 [CHK-2442] feat: added correlationId into openapi for POST v2/transactions
  api-spec/v2/transactions-api.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/data/NewTransactionRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/mdcutilities/MDCFilter.java
  src/main/java/it/pagopa/transactions/mdcutilities/TransactionTracingUtils.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
Labels: size/small, minor, chart-minor

#422 feat: add integration with node forwarder
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilder.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilder.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilderTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilderTest.java
  src/test/resources/application-tests.properties
Labels: size/large, minor, chart-minor

#425 feat: remove unused postepay logic
  api-spec/v1/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
Labels: size/small, patch, chart-patch

#432 CHK-2479 - handle payment method and payment method id redirect retrieve url api body fields
  api-spec/client/openapi/redirect/redirect-api.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
Labels: size/small, patch, chart-patch

#435 chore(conf): configure Intesa redirect parameters
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#433 feat: added correlationId exception 400
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
Labels: size/small, skip-release, ignore-for-release

#430 [CHK-2452] add business logic to handle get state in transactions service
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureRequestedHandlerTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#436 [CHK-2470] session token into outcome URL
  .env.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/utils/NpgBuildData.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/utils/NpgOutcomeUrlMatcher.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor

#441 fix: add exception logging for node forwarder errors
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
Labels: size/small, patch, chart-patch

#438 fix(conf): configure Mongo driver connection options
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch

#443 fix: helm values for uat and prod
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#444 feat(deps): [CHK-2534] - update opentelemetry agent to v2.1.0
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: size/small, patch, chart-patch

#440 refactor(npg): add error code field to `PATCH /auth-requests` for NPG
  api-spec/v1/transactions-api.yaml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Labels: size/small, patch, chart-patch
