Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-01, with the labels that each got.

#388 Chk 2258 update wallet client
  pom.xml
  src/main/java/it/pagopa/transactions/client/WalletClient.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/WalletClientTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: minor, chart-minor

#385 feat: order build for apm transaction
  .env.example
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/client/WalletClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/NpgWebClientConfigTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/client/WalletClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: minor, chart-minor

#390 feat: [CHK-1935] elastic dashboard for auth request
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionInitializerHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: size/small, minor, chart-minor

#392 [CHK-1936] Add user receipt dashboard
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
Labels: size/small, minor, chart-minor

#396 [CHK-2321] feat(checkout-redirect): add secret that holds PSPs' API keys
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectPspApiKeysConfigBuilder.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/resources/application.properties
  src/test/resources/application-tests.properties
Labels: patch, chart-patch

#398 CHK-2319 - feat: redirect business logic
  .env.example
  README.md
  api-spec/v1/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilder.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilder.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectPspApiKeysConfigBuilder.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectUrlMapping.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/LogoMappingUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilderTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilderTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor

#397 [CHK-2319] - checkout redirect implementation api client configuration
  .env.example
  README.md
  api-spec/client/openapi/redirect/redirect-api.yaml
  api-spec/v1/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilder.java
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilder.java
  src/main/java/it/pagopa/transactions/configurations/CheckoutRedirectPspApiKeysConfigBuilder.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/LogoMappingUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/CheckoutRedirectClientBuilderTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/configurations/CheckoutRedirectConfigurationsBuilderTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/resources/application-tests.properties
Labels: size/large, minor, chart-minor

#401 fix: helm values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#402 [CHK-2380] deployment strategy
  helm/values-dev.yaml
  helm/values-prod.yaml
  src/main/resources/application.properties
Labels: size/small

#406 feat: enable ff to handle sendpaymentresult for expired transaction
  helm/values-prod.yaml
Labels: size/small, minor, chart-minor

#409 [CHK-2380] add deployment node for prod
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#414 fix(spec misalignment): rename misaligned fields
  api-spec/v1/transactions-api.yaml
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, patch, chart-patch
