Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-10, with the labels that each got.

#577 Feat: [CHK-3246] Added logic to send lang header
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/TransactionRequestAuthorizationCommand.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor

#579 [CHK-3291] Save last payment method by user
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, minor, chart-minor

#581 [CHK-3267] feat: reduce logging size
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/mdcutilities/MDCContextLifter.java
  src/main/java/it/pagopa/transactions/mdcutilities/MDCFilter.java
Labels: size/small, patch, chart-patch

#582 fix: [CHK-3267] reactor context key
  src/main/java/it/pagopa/transactions/mdcutilities/MDCContextLifter.java
Labels: size/small, patch, chart-patch

#583 [CHK-3316] set last used method saving timeout to 0
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#584 [CHK-3338] feat: remove old last usage method
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/WalletAsyncQueueClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/WalletAsyncQueueClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureRequestedHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUserCancelHandlerTest.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor
