Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-03, with the labels that each got.

#451 feat(ff): send payment result after expiration for v2 events
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
Labels: size/small, minor, chart-minor

#455 fix: error mapping for patch auth request with missing auth requested event
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#454 [CHK-2575] refactor(redirect): update commons
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusDataTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Labels: size/small, patch, chart-patch

#458 [CHK-2554] fix: spotless
  src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
Labels: size/small, patch, chart-patch

#457 feat: CHK-1938 add an API id in log context
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/mdcutilities/TransactionTracingUtils.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
Labels: size/small, minor, chart-minor

#460 CHK-1938: log enrichment
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
Labels: size/small, patch, chart-patch

#459 feat: derive logos from payment method calculate fee response body
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestSessionData.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/BrandLogoConfig.java
  src/main/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilder.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/LogoMappingUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/configurations/BrandLogoConfigTest.java
  src/test/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilderTest.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/java/it/pagopa/transactions/utils/LogoMappingUtilsTest.java
  src/test/resources/application-tests.properties
Labels: size/large, minor, chart-minor

#461 feat: change redirect url mapping key
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilder.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilderTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch
