Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-05, with the labels that each got.

#484 fix(logging): handle multiple rpt ids into logs
  src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionAddUserReceiptCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionClosureRequestCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionClosureSendCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionRequestAuthorizationCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionUpdateAuthorizationCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionUserCancelCommand.java
  src/main/java/it/pagopa/transactions/commands/TransactionsCommand.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
Labels: size/small, patch, chart-patch

#481 chore: add beta for testing nodo dev
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#483 feat(carts): add v2 client
  .env.example
  .env.intellij.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestSessionData.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
  src/test/java/it/pagopa/transactions/configurations/WebClientsConfigTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#486 feat(user notification): use company name from activate instead from sendPaymentResult
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor

#489 [CHK-2828] Check user in transactions operations
  api-spec/v1/transactions-api.yaml
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/repositories/TransactionsViewRepository.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#468 feat(node-error): CHK-2701 update node error hanlder for V2 Transactions
  api-spec/v2/transactions-api.yaml
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
Labels: size/large, minor, chart-minor

#493 fix(test): controller v2 transactions
  helm/values-uat.yaml
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
Labels: size/small, patch, chart-patch

#491 fix(perf): ndots
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
Labels: size/small, patch, chart-patch

#501 fix: avoid retry on gateway auth request with 4xx response code
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
Labels: size/small, patch, chart-patch

#503 fix: add span to tracing circuit breaker
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#505 [CHK-2882] [CHK-2884] fix(auth-request) remove requestTransactionAuthorization circuit breaker
  helm/values-prod.yaml
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
Labels: size/small, patch, chart-patch

#509 chore(NPG-conf): add mandatory cards and MyBanks psp api key
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#508 fix(NPG auth request): error codes to be excluded for retry
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/NpgNotRetryableErrorException.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/resources/application-tests.properties
Labels: patch, chart-patch

#511 fix(auth-request): add 422 error response code
  api-spec/v1/transactions-api.yaml
Labels: size/small, patch, chart-patch
