Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-07, with the labels that each got.

#535 fix(conf): add required npg api keys
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#540 [CHK-3030] feat(auth): add session token in authorization redirect url when used for transactions by IO app
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureRequestHandler.java
  src/main/java/it/pagopa/transactions/configurations/SecretsConfigurations.java
  src/main/java/it/pagopa/transactions/repositories/TransactionTemplateWrapper.java
  src/main/java/it/pagopa/transactions/repositories/TransactionsViewRepository.java
  src/main/java/it/pagopa/transactions/utils/UUIDUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/TransactionUtilTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/TransactionAuthorizationHandlerCommon.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureRequestedHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v2_1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
  src/test/java/it/pagopa/transactions/utils/UUIDUtilsTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#544 chore(helm): increase min replicas to 5
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#545 fix: Dummy patch for release
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#538 feat(npg-apm): add configuration for apple pay and satispay
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigBuilder.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#541 [CHK-3034] feat: enable PSP iConto for cards payments in prod
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#547 feat: add locking for avoid multiple patch processing
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/configurations/RedisConfig.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/LockNotAcquiredException.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor

#548 fix(redirect): userId for redirect authorization
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#542 [CHK-3037] feat: enable PSP Unicredit for MyBank payments in prod
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#550 [CHK-3076] chore(helm): align UAT's NPG_AUTHORIZATION_REQUEST_TIMEOUT_SECONDS
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#551 [CHK-3055] Add span for send payment result monitoring
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/configurations/OpenTelemetryConfiguration.java
  src/main/java/it/pagopa/transactions/controllers/v1/SendPaymentResultOutcomeInfo.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2_1/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/AlreadyProcessedException.java
  src/main/java/it/pagopa/transactions/exceptions/InvalidRequestException.java
  src/main/java/it/pagopa/transactions/exceptions/ProcessingErrorException.java
  src/main/java/it/pagopa/transactions/exceptions/SendPaymentResultException.java
  src/main/java/it/pagopa/transactions/exceptions/TransactionContext.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/main/java/it/pagopa/transactions/utils/SpanLabelOpenTelemetry.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/java/it/pagopa/transactions/utils/OpenTelemetryUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: size/large, minor, chart-minor

#552 [CHK-3054] feat: add PSP and payment type code to authorization outcome metrics
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/configurations/OpenTelemetryConfiguration.java
  src/main/java/it/pagopa/transactions/configurations/UpdateTransactionStatusTracerUtilsConfig.java
  src/main/java/it/pagopa/transactions/controllers/v1/SendPaymentResultOutcomeInfo.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2_1/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/AlreadyProcessedException.java
  src/main/java/it/pagopa/transactions/exceptions/InvalidRequestException.java
  src/main/java/it/pagopa/transactions/exceptions/ProcessingErrorException.java
  src/main/java/it/pagopa/transactions/exceptions/SendPaymentResultException.java
  src/main/java/it/pagopa/transactions/exceptions/TransactionContext.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
  src/main/java/it/pagopa/transactions/utils/SpanLabelOpenTelemetry.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/java/it/pagopa/transactions/utils/OpenTelemetryUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: size/large, patch, chart-patch
