Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-04, with the labels that each got.

#465 feat(npg-apm): api keys configuration for APM
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigBuilder.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#466 [CHK-2686] feat(apm): auth-request for apm
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, patch, chart-patch

#470 feat: save user id into transaction activated event
  api-spec/v2/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
  src/main/java/it/pagopa/transactions/commands/data/NewTransactionRequestData.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor

#472 fix: commons library ref
  pom.xml
Labels: size/small, skip-release

#476 refactor(redis): use new refs for redis
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#469 [CHK-2710] Wallet Last Usage implementation
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/WalletAsyncQueueClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/WalletAsyncQueueClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#477 feat(monitoring): trace gateway outcome tracing
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtils.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/utils/UpdateTransactionStatusTracerUtilsTest.java
Labels: size/small, minor, chart-minor

#473 feat(NPG): [CHK-2733] - save POST notification validationServiceId field into events
  api-spec/v1/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
Labels: size/small, minor, chart-minor

#479 fix(payment-methods): add exception mapping and logging when erroring in `GET /payment-methods/:id`
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/exceptions/PaymentMethodNotFoundException.java
  src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#480 fix: add missing circuit breaker config for `PaymentMethodNotFoundException`
  src/main/resources/application.yml
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
Labels: size/small, patch, chart-patch

#482 chore(conf): add mooney as paypal psp
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, skip-release, chart-minor
