Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-06, with the labels that each got.

#513 fix(auth-request): add parameter binding
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
Labels: size/small, patch, chart-patch

#515 [CHK-2861] fix(jwttoken): userId in jwt token
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/utils/JwtTokenUtilsTests.java
Labels: size/small, minor, chart-minor

#506 [CHK-2868] Add touchpoint parameter to redirectUrls search.
  .env.example
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilder.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/configurations/RedirectConfigurationsBuilderTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#517 fix: [CHK-2897] Increase delay for first NPG GET state
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#521 chore(conf npg cards): add WOLLNLB1 psp id
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#522 chore(chart): increase prod memory limit to 768
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#524 [CHK-2914, CHK-2915] refactor: use outcome url in place of dedicated cancellation url
  .devops/deploy-pipelines.yml
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/configurations/NpgSessionUrlConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#526 chore(conf): increase node forwarder UAT timeouts
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#527 chore: Alert OPEX x apim V2
  .github/workflows/create_dashboard.yaml
  .gitignore
  .opex/apim_v1/env/prod/backend.ini
  .opex/apim_v1/env/prod/backend.tfvars
  .opex/apim_v1/env/prod/config.yaml
  .opex/apim_v1/env/prod/terraform.tfvars
  .opex/apim_v1/env/uat/backend.ini
  .opex/apim_v1/env/uat/backend.tfvars
  .opex/apim_v1/env/uat/config.yaml
  .opex/apim_v1/env/uat/terraform.tfvars
  .opex/apim_v2/env/prod/backend.ini
  .opex/apim_v2/env/prod/backend.tfvars
  .opex/apim_v2/env/prod/config.yaml
  .opex/apim_v2/env/prod/terraform.tfvars
Labels: size/small, skip-release

#528 fix: Dash step2
  .github/workflows/create_dashboard.yaml
Labels: size/small

#520 [CHK-2881] fix(auth-request): handle payment complete case from npg
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, patch, chart-patch

#529 chore: Gha opex refactoring
  .github/workflows/create_dashboard.yaml
  .opex/apim_v1/env/uat/backend.ini
  .opex/apim_v1/env/uat/backend.tfvars
  .opex/apim_v1/env/uat/config.yaml
  .opex/apim_v1/redirect/env/prod/backend.ini
  .opex/apim_v1/redirect/env/prod/backend.tfvars
  .opex/apim_v1/redirect/env/prod/config.yaml
  .opex/apim_v1/redirect/env/prod/terraform.tfvars
  .opex/apim_v1/trx_v1/env/prod/backend.ini
  .opex/apim_v1/trx_v1/env/prod/backend.tfvars
  .opex/apim_v1/trx_v1/env/prod/config.yaml
  .opex/apim_v1/trx_v1/env/prod/terraform.tfvars
  .opex/apim_v1/trx_v2/env/prod/backend.ini
  .opex/apim_v1/trx_v2/env/prod/backend.tfvars
  .opex/apim_v1/trx_v2/env/prod/config.yaml
  .opex/apim_v1/trx_v2/env/prod/terraform.tfvars
  .opex/apim_v2/redirect/env/prod/backend.ini
  .opex/apim_v2/redirect/env/prod/backend.tfvars
  .opex/apim_v2/redirect/env/prod/config.yaml
  .opex/apim_v2/redirect/env/prod/terraform.tfvars
  .opex/apim_v2/trx_v1/env/prod/backend.ini
  .opex/apim_v2/trx_v1/env/prod/backend.tfvars
  .opex/apim_v2/trx_v1/env/prod/config.yaml
  .opex/apim_v2/trx_v1/env/prod/terraform.tfvars
  .opex/apim_v2/trx_v2/env/prod/backend.ini
  .opex/apim_v2/trx_v2/env/prod/backend.tfvars
  .opex/apim_v2/trx_v2/env/prod/config.yaml
  .opex/apim_v2/trx_v2/env/prod/terraform.tfvars
Labels: size/small, skip-release

#531 update card psp lists
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#533 chore(conf): set redirect psp ids
  helm/values-prod.yaml
Labels: size/small, chart-patch, ignore-for-release

#530 [CHK-2955] refactor: move payment session update on payment methods before call to NPG gateway
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Labels: size/small, patch, chart-patch

#534 feat(pspList): add pspId IFSPIT21 to pspIdList
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release
