Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2024-09, with the labels that each got.

#558 feat: [CHK-3109] Handle payment notice IUV
  api-spec/v2.1/transactions-api.yaml
  api-spec/v2/transactions-api.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
  src/main/java/it/pagopa/transactions/services/v2_1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
  src/main/java/it/pagopa/transactions/utils/WispDeprecation.java
  src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2_1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
  src/test/java/it/pagopa/transactions/utils/TransactionsUtilsTest.java
Labels: size/small, minor, chart-minor

#567 fix: wrong clientId outcome url
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
Labels: size/small, patch, chart-patch

#561 [CHK-3135] remove xpay vpos references
  .devops/code-review-pipelines.yml
  .env.example
  .env.intellij.example
  README.md
  api-spec/v1/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusDataTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
  src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
  src/test/resources/application-tests.properties
Labels: size/large, patch, chart-patch

#570 feat: [CHK-3217] Upgrade helm chart + autoscaling limits
  .devops/code-review-pipelines.yml
  helm/Chart.lock
  helm/Chart.yaml
  helm/charts/microservice-chart-2.3.1.tgz
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, minor, chart-minor

#571 [CHK-3204] feat: update api tests refs
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#572 fix: [CHK-3224] reduce initial delay for liveness and readiness
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch

#574 fix: avoid multiple auth requests for same transaction
  .env.example
  .env.intellij.example
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
Labels: size/small, patch, chart-patch

#575 fix: move lock before interacting with gateway
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/resources/application.yml
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
Labels: size/small, patch, chart-patch

#573 [CHK-3244] Update open api v2 to include an optional "lang" header
  api-spec/v1/transactions-api.yaml
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
Labels: size/small, minor, chart-minor
