Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2025-06, with the labels that each got.

#638 fix(ecommerce-amount): PIDM-614 increase max amount spec
  api-spec/v2.1/transactions-api.yaml
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
Labels: size/small, patch, chart-patch

#640 fix(huge-amount): update v1 and v2 api with huge amount spec
  api-spec/v1/transactions-api.yaml
  api-spec/v2/transactions-api.yaml
Labels: size/small, patch, chart-patch

#643 Revert "Revert "[CHK-4002] Added api key (#609)" (#612)"
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#644 Chk 4173 post transactions jwt issuer revert
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/transactions/client/JwtTokenIssuerClient.java
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandlerCommon.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/configurations/JWTIssuerWebClientConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/JwtTokenIssuerClientTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/resources/application-tests.properties
Labels: patch, chart-patch

#632 feat(activatePayment): add transactionId as header for activate (nodo)
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/java/it/pagopa/transactions/utils/NodoOperations.java
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Labels: size/small, minor, chart-minor

#647 [CHK-4225] chore(mongo): add replica set to mongo connection string
  README.md
  helm/values-prod.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch

#649 fix: code deprecations
  pom.xml
  src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
  src/main/java/it/pagopa/transactions/repositories/TransactionCacheInfo.java
  src/main/java/it/pagopa/transactions/repositories/WalletPaymentInfo.java
  src/test/java/it/pagopa/transactions/PagopaEcommerceTransactionsApplicationTests.java
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#652 PDM-710: add helm valuest for klarna
  .env.example
  .env.intellij.example
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch
