Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2025-02, with the labels that each got.

#603 chore: remove log mask feature falling back to the default ecs encoder
  src/main/java/it/pagopa/transactions/utils/EcsEncoderLogMasker.java
  src/main/resources/logback-spring.xml
  src/test/java/it/pagopa/transactions/utils/EcsEncoderExceptionTest.java
  src/test/java/it/pagopa/transactions/utils/EcsEncoderLogMaskerTests.java
  src/test/java/it/pagopa/transactions/utils/LogFormatterTests.java
Labels: size/small, patch, chart-patch

#604 [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions
  .devops/azure-templates/maven-github-release.yml
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release, ignore-for-release

#605 [PIDM-134] Handle retry on add user receipt
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/exceptions/InvalidStatusException.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
Labels: size/small, minor, chart-minor

#606 chore: update github release task
  .devops/azure-templates/maven-github-release.yml
Labels: size/small, patch, chart-patch
