Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2025-04, with the labels that each got.

#609 [CHK-4002] Added api key
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#611 feat: add specs for patch auth request v2
  api-spec/v2/transactions-api.yaml
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
Labels: minor, chart-minor

#612 chore: Revert "[CHK-4002] Added api key (#609)"
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, patch, chart-patch

#613 feat: add npg google pay api key management
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigBuilder.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/configurations/NpgPspApiKeysConfigTest.java
  src/test/resources/application-tests.properties
Labels: minor, chart-minor

#615 feat(transaction-view): add paymentTypeCode and pspId in view
  pom.xml
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandler.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor

#618 [CHK-4070] chore(v1-handlers): remove unused handlers
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureErrorProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/ClosureSendProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/RefundRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/main/java/it/pagopa/transactions/utils/EventVersion.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandlerTest.java
  src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionsActivationProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/ClosureErrorProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/ClosureSendProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/RefundRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
  src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/large, skip-release, ignore-for-release

#617 [PIDM-454] fix: expanded prod rollback trigger conditions
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#622 fix: deploy pipeline version bump
  .devops/azure-templates/maven-github-release.yml
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/semver_release.yaml
Labels: size/large, patch, chart-patch
