Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2025-07, with the labels that each got.

#651 feat: protect all api by api key
  .env.example
  .env.intellij.example
  README.md
  api-spec/v1/transactions-api.yaml
  api-spec/v2.1/transactions-api.yaml
  api-spec/v2/transactions-api.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/controllers/filters/ApiKeyFilter.java
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
  src/main/java/it/pagopa/transactions/controllers/v2_1/TransactionsController.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/controllers/filters/ApiKeyFilterTest.java
  src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
  src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#655 [CHK-4288] feat(api-key): add api key to jwt-issuer webclient
  .devops/code-review-pipelines.yml
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/transactions/client/JwtTokenIssuerClient.java
  src/main/java/it/pagopa/transactions/configurations/JWTIssuerWebClientConfig.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/transactions/client/JwtTokenIssuerClientTest.java
  src/test/resources/application-tests.properties
Labels: size/small, minor, chart-minor

#653 feat: [CHK-4218] upgrade java version to 21
  .devops/code-review-pipelines.yml
  .java-version
  Dockerfile
  README.md
  pom.xml
  src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
Labels: size/small, major, chart-major

#657 [PIDM] Revert "[CHK-4225] chore(mongo): add replica set to mongo connection"
  README.md
  helm/values-prod.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch

#662 feat(cdc-field): [CHK-4349] add lastProcessedEventAt to transactions-view
  pom.xml
  src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestedEventData.java
  src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
  src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandlerTests.java
  src/test/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, minor, chart-minor
