Repository pagopa/pagopa-ecommerce-transactions-service, pull requests merged in 2025-09, with the labels that each got.

#667 feat(build): [CHK-4379] add github token
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  Dockerfile
  README.md
  pom.xml
  settings.xml.template
Labels: size/small, minor, chart-minor

#676 feat: [CHK-4405] adding dependencies verification
  README.md
  dep-sha256.json
  pom.xml
Labels: size/large, skip-release

#684 fix: subscribe to delete mono
  src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
  src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
  src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
  src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Labels: size/small, patch, chart-patch

#681 [CHK-4428] restore template usage and add token file creation
  .devops/deploy-pipelines.yml
Labels: size/small, patch, chart-patch
